added cache for did-resolver
TBD54566975/dwn-sdk-js pull request #155
Opened 2022-11-16 13:50 UTC by Cxxshyy

Wanted to use this new branch i created for the Pull request if thats ok

2022-11-21 19:37 UTC, thehenrytsai commented on src/did/did-resolver.ts
> +    const isCached = await this.cache.get(did) !== undefined;
`await this.cache.get(did)` is called 3 times, please reduce it to just once

2022-11-21 19:37 UTC, thehenrytsai commented on src/did/did-resolver.ts
> +    }
No need to have an empty `else` block.

2022-11-21 19:41 UTC, thehenrytsai commented on tests/did/did-resolver.spec.ts
> +  it('should pick the right DID resolver based on DID method name and account for passed in cache', async () => {
The test seems unrelated to the addition of a cache and does not cover the code added. The test should be along the lines of:

"should read from cache and not from resolver if cache contains the DID resolution result"

2022-11-21 19:41 UTC, thehenrytsai requested changes
Thanks @Cxxshyy! Some suggestions.

2022-11-21 19:56 UTC, Cxxshyy commented
not to sure whether you meant for the test to be like this but is this what you meant?

2022-11-21 20:01 UTC, Cxxshyy commented
im confused why integrity check failed as i just tested and they all passed

2022-11-21 23:50 UTC, thehenrytsai commented on src/did/did-resolver.ts
> +    const isCached = await this.cache.get(did);
```suggestion
    const cachedResolutionResult = await this.cache.get(did);
```

2022-11-21 23:51 UTC, thehenrytsai commented on src/did/did-resolver.ts
> +    const resolutionResult = isCached !== undefined ? isCached : await didResolver.resolve(did);
```suggestion
    const resolutionResult = cachedResolutionResult ?? await didResolver.resolve(did);
```

2022-11-21 23:58 UTC, thehenrytsai commented
> not to sure whether you meant for the test to be like this but is this what you meant?

Not quite, see PR https://github.com/TBD54566975/dwn-sdk-js/commit/4d5d983c23cb5f72459a98c3a84128b5af6913c6 for test example, basically you want to make sure resolution for the SAME DID doesn't call the resolver twice (i.e. once hitting the resolver, and once hitting the cache)

> im confused why integrity check failed as i just tested and they all passed

Most likely because more code has been merged into `main` branch, and there is conflict with your PR (looks like just README.md for now). In case you didn't know, you can either run git commands and fix conflicts locally, or you can use the github UI to resole the conflicts.

2022-11-23 04:13 UTC, michaelneale commented
this in reasonable shape now to merge?

2022-11-23 12:05 UTC, Cxxshyy commented
@michaelneale need some amendments first ill do them now

2022-11-23 12:30 UTC, Cxxshyy commented
@thehenrytsai sorry if i still dont understand but what i done was check cache to see if result is there and if not call resolver then store that result in cache

2022-11-29 02:05 UTC, thehenrytsai commented
@Cxxshyy, I have gone ahead and made the changes I was thinking off to your PR: https://github.com/Cxxshyy/dwn-sdk-js/pull/1, please take a look and approve, then I can merge!

2022-11-29 05:51 UTC, thehenrytsai commented
> @thehenrytsai it is often possible to push directly to the @Cxxshyy#1 branch (yes - the remote branch! usually github allows it with forked PRs, which I know sounds weird but works the same as a branch based PR).

Wow, this is super weird (but also super cool) instead, would've have thought one would need explicit permission from the repo owner, I guess it's implied!! Merging it!

2022-11-29 05:53 UTC, merged