npm release automation from a tag
TBD54566975/dwn-sdk-js pull request #177
Opened 2023-01-03 06:46 UTC by michaelneale

this is the first pass at release automation for npm - using the off the shelf github action recommendation

2023-01-03 06:47 UTC, michaelneale commented
cc @thehenrytsai @frankhinek for your consideration

2023-01-03 22:41 UTC, thehenrytsai commented on .github/workflows/npm-publish.yml
> +      - run: npm ci
Sanity: there isn't a `ci` script

2023-01-03 22:42 UTC, thehenrytsai commented on .github/workflows/npm-publish.yml
> +      - run: npm test
Sanity:
```suggestion
      - run: npm run test:node:ci
```

2023-01-03 22:45 UTC, thehenrytsai requested changes
Looks like this is the first attempt at the automated release and needing for the code to be checked in to actually test it.

2023-01-03 22:46 UTC, michaelneale commented
I need to make some changes: don't really want to run tests as part of this - @thehenrytsai what command do you run to npm publish today?

2023-01-03 22:48 UTC, michaelneale commented on .github/workflows/npm-publish.yml
> +          node-version: 16
> Looks like this is the first attempt at the automated release and needing for the code to be checked in to actually test it.

yes - I was testing this in a different repo with a dummy package first.

2023-01-04 01:18 UTC, thehenrytsai commented
I do an `npm version path/minor` followed by `npm publish` for "official" release. For "unstable" release, I manually update the version in `pacakge.json` to look like [`0.0.13-unstable-20221208-1`](https://www.npmjs.com/package/@tbd54566975/dwn-sdk-js/v/0.0.13-unstable-20221208-1), then `npm publish`.

As of now, I am more interested in the automation for the unstable release (say after each commit to `main` branch), but this is a great first step!

2023-01-04 01:21 UTC, thehenrytsai commented
For reference, [this](https://github.com/decentralized-identity/sidetree/blob/master/.github/workflows/unstable-release.yml) is what `sidetree` repo did for unstable release a couple of years back, the state of art might have changed now.

2023-01-05 07:04 UTC, michaelneale commented
ok @thehenrytsai please take another look - borrowed the sidetree approach so that main deploys will be deployed as unstable but with a handy timestamp (and proper releases can be created from github releases - but it will just use the package.json version in that case) - as I think that releases can be "press the button" for now

2023-01-05 18:57 UTC, thehenrytsai approved these changes
Let's give this a go! 🎉 🎊

2023-01-05 19:38 UTC, merged