Added tests to demonstrate direct child-role authorization in slack-like protocol
TBD54566975/dwn-sdk-js pull request #696
Opened 2024-02-26 21:15 UTC by thehenrytsai

2024-02-26 21:28 UTC, LiranCohen requested changes
Looks good! Just forgot the `.only` in the test.

2024-02-26 21:28 UTC, LiranCohen commented on tests/scenarios/nested-roles.spec.ts
> +    it.only('should support Slack-like protocol with community and gated channels', async () => {
```suggestion
    it('should support Slack-like protocol with community and gated channels', async () => {
```

2024-02-26 21:36 UTC, thehenrytsai commented on tests/scenarios/nested-roles.spec.ts
> +    it.only('should support Slack-like protocol with community and gated channels', async () => {
Thanks for the lightning fast review!

2024-02-27 02:07 UTC, LiranCohen approved these changes

2024-02-27 18:01 UTC, merged