feat/78-message-create-input-property-validation
TBD54566975/dwn-sdk-js pull request #79
Opened 2022-08-08 16:46 UTC by virajjiwane

Add input property validation for all message create() methods #78

2022-08-08 19:12 UTC, thehenrytsai requested changes
@virajjiwane, thanks for working on this and submitting this PR!

The issue is specifically hoping that we can reuse the JSON schema [validation code](https://github.com/TBD54566975/dwn-sdk-js/blob/main/src/validation/validator.ts#L20) that we already have so we minimize extra code.

Also `CollectionsWrite` is newly checked in so also needs the same validation.

2022-08-09 04:03 UTC, virajjiwane commented
Hi @thehenrytsai, thanks for the reply. I understood the requirement, will work on the changes.

2022-08-10 03:49 UTC, virajjiwane commented
@thehenrytsai changes done. please review

2022-08-15 17:44 UTC, thehenrytsai requested changes
Thanks for adding the change, almost there, a couple of comments.

2022-08-15 17:44 UTC, thehenrytsai commented on src/interfaces/collections/messages/collections-write.ts
> +    const messageType = descriptor['method'];
```suggestion
    const messageType = descriptor.method;
```

2022-08-15 17:44 UTC, thehenrytsai commented on src/interfaces/collections/messages/collections-write.ts
> +    validate(messageType, message);
validate before `await sign(...)` since signing it costly.

2022-08-16 17:35 UTC, virajjiwane commented
@thehenrytsai did changes in all Message create methods and moved validation before any auth functions I could find. please review again.

2022-08-17 19:19 UTC, merged